import axios from "axios";
import crypto from "crypto";
const USERS = ["102729471983875601261", "107049034776881783285", "coocent01", "coocent02", "coocent03", "coocent04", "coocent05", "coocent21", "coocent22", "coocent31"];
class CoocentAI {
  constructor() {
    this.baseUrl = "https://agent.coocent.com";
    this.salt = "Coocent@Agent";
    this.headers = {
      "User-Agent": "okhttp/4.12.0",
      "Content-Type": "application/json; charset=UTF-8",
      "package-name": "drum.pads.beat.drumpadmachine",
      "app-version": "1.0.0"
    };
  }
  hash(str) {
    return crypto.createHash("md5").update(str).digest("hex");
  }
  enc(userId, taskId) {
    return Buffer.from(JSON.stringify({
      userId: userId,
      taskId: taskId
    })).toString("base64");
  }
  dec(state) {
    try {
      return JSON.parse(Buffer.from(state, "base64").toString("utf8"));
    } catch (err) {
      console.error(`[dec] invalid state:`, err?.message);
      throw new Error("[dec] failed to decode state");
    }
  }
  async req(method, path, data = null, params = null) {
    const url = `${this.baseUrl}/${path}`;
    console.log(`[req] ${method.toUpperCase()} ${url}`, params ?? data ?? "");
    try {
      const res = await axios({
        method: method,
        url: url,
        data: data,
        params: params,
        headers: this.headers
      });
      console.log(`[req] response:`, JSON.stringify(res.data, null, 2));
      return res.data;
    } catch (err) {
      console.error(`[req] error ${method.toUpperCase()} ${url}:`, err?.message);
      console.error(`[req] error detail:`, JSON.stringify(err.response?.data, null, 2));
      return err.response?.data || {
        head: {
          code: 500,
          msg: err.message
        }
      };
    }
  }
  async login(userId) {
    console.log(`[login] user: ${userId}`);
    try {
      const res = await this.req("POST", "music/login", {
        user_id: userId,
        name: userId,
        picture: "",
        email: ""
      });
      console.log(`[login] done:`, res?.head?.msg ?? "ok");
      return res;
    } catch (err) {
      console.error(`[login] failed ${userId}:`, err?.message);
      throw err;
    }
  }
  async create({
    id,
    ...rest
  }) {
    console.log(`[create] start`, {
      id: id,
      ...rest
    });
    try {
      const {
        title = "My AI Song",
          lyrics = "Generated by Coocent AI",
          gender = "male",
          timbre = "bright",
          genre = "pop",
          emotion = "happy",
          instrument = "piano",
          genType = "bgm",
          coverArt = "",
          duration = 120,
          cost = 5,
          utype = "ai"
      } = rest;
      const queue = id ? [id] : [...USERS].sort(() => Math.random() - .5);
      console.log(`[create] attempt queue:`, queue);
      let lastRes = null;
      for (const userId of queue) {
        console.log(`[create] trying user: ${userId}`);
        await this.login(userId);
        const ts = Date.now().toString();
        const sign = this.hash(this.salt + userId + cost + ts);
        const payload = {
          user_id: userId,
          title: title,
          lyrics: lyrics,
          gender: gender,
          timbre: timbre,
          genre: genre,
          emotion: emotion,
          instrument: instrument,
          gen_type: genType,
          cover_art: coverArt,
          duration: duration,
          cost: cost,
          utype: utype,
          ts: ts,
          sign: sign
        };
        const res = await this.req("POST", "music/gentask", payload);
        lastRes = {
          userId: userId,
          res: res
        };
        const code = res?.head?.code ?? res?.code ?? 0;
        console.log(`[create] user ${userId} → code: ${code}, msg: ${res?.head?.msg ?? "-"}`);
        if (code === 200) {
          const taskId = res?.data?.user_taskid ?? null;
          console.log(`[create] success! taskId: ${taskId}`);
          const state = this.enc(userId, taskId);
          console.log(`[create] state: ${state}`);
          const {
            data,
            ...info
          } = res;
          return {
            state: state,
            ...info
          };
        }
        console.warn(`[create] skip ${userId}: ${res?.head?.msg ?? "failed"}`);
      }
      console.error(`[create] all users exhausted`);
      const {
        data,
        ...info
      } = lastRes?.res ?? {};
      return {
        state: null,
        ...info
      };
    } catch (err) {
      console.error(`[create] failed:`, err?.message);
      throw err;
    }
  }
  async status({
    state,
    ...rest
  }) {
    if (!state) throw new Error("[status] state is required");
    console.log(`[status] decoding state...`);
    try {
      const {
        userId,
        taskId
      } = this.dec(state);
      console.log(`[status] userId: ${userId}, taskId: ${taskId}`);
      const res = await this.req("GET", "music/getusersong", null, {
        user_id: userId,
        ...rest
      });
      console.log(`[status] done`, res?.head ?? res);
      const list = res?.data ?? res?.result ?? [];
      const songs = Array.isArray(list) ? list : [list];
      const result = taskId ? songs.find(s => s?.user_taskid === taskId || s?.id === taskId) ?? songs[0] ?? null : songs[0] ?? null;
      console.log(`[status] song found: ${result?.id ?? "none"} (task: ${result?.user_taskid ?? "-"})`);
      const {
        data,
        ...info
      } = res;
      return {
        result: result,
        ...info
      };
    } catch (err) {
      console.error(`[status] failed:`, err?.message);
      throw err;
    }
  }
}
export default async function handler(req, res) {
  const {
    action,
    ...params
  } = req.method === "GET" ? req.query : req.body;
  const validActions = ["create", "status"];
  if (!action) {
    return res.status(400).json({
      status: false,
      error: "Parameter 'action' wajib diisi.",
      available_actions: validActions,
      usage: {
        method: "GET / POST",
        example: "/?action=create&title=test"
      }
    });
  }
  const api = new CoocentAI();
  try {
    let response;
    switch (action) {
      case "create":
        if (!params.lyrics) {
          return res.status(400).json({
            status: false,
            error: "Parameter 'lyrics' wajib diisi untuk action 'create'."
          });
        }
        response = await api.create(params);
        break;
      case "status":
        if (!params.state) {
          return res.status(400).json({
            status: false,
            error: "Parameter 'state' wajib diisi untuk action 'status'."
          });
        }
        response = await api.status(params);
        break;
      default:
        return res.status(400).json({
          status: false,
          error: `Action tidak valid: ${action}.`,
          valid_actions: validActions
        });
    }
    return res.status(200).json({
      status: true,
      action: action,
      ...response
    });
  } catch (error) {
    console.error(`[FATAL ERROR] Kegagalan pada action '${action}':`, error);
    return res.status(500).json({
      status: false,
      message: "Terjadi kesalahan internal pada server.",
      error: error.message || "Unknown Error"
    });
  }
}